{% set name = "condor" %}
{% set version = "1.0.7a" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_tag: master
  git_url: https://github.com/FXIhub/condor.git

build:
  number: {{ build }}
  # There are dependency conflicts for Python 2 on Windows
  skip: True  # [win and py<30]
  # There are dependency conflicts for Python 3.8 on Windows
  skip: True  # [win and py>=38]
  # To start with
  skip: True  # [py != 37]

  
requirements:
  build:
    - git
    - {{ compiler('c') }} # [not osx]
    
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - h5py
    - nfft

  run:
    - python 
    - numpy
    - scipy
    - h5py
    - nfft
    - libspimage

test:
  imports:
    - condor

about:
  home: https://github.com/FXIhub/condor
  license: BSD
  license_file: copyright
  summary: A simulation tool for flash X-ray imaging

extra:
  recipe-maintainers: 'FilipeMaia'
