package:
  name: condor
  version: '1.0.6'

source:
  git_rev: 1.0.6
  git_url: https://github.com/FXIhub/condor.git

requirements:
  host:
    - python
    - setuptools
    - numpy
    - scipy
    - h5py
    - nfft

  run:
    - python 
    - numpy
    - scipy
    - h5py
    - nfft

test:
  imports:
    - condor

about:
  home: https://github.com/FXIhub/condor
  license: BSD
  license_file: copyright
  summary: A simulation tool for flash X-ray imaging

extra:
  recipe-maintainers: 'FilipeMaia'
